### ISSUE TITLE
CUDA not using the right version of gcc

### ISSUE THREAD

**Issue by JeremieBourque1** [timongentzsch/Jetson_Ubuntu20_Images#1]
Hi,

I am trying to build the Intel RealSense SDK, builds with CUDA, inside a docker image and using your timongentzsch/l4t-ubuntu20-base:latest image as a base.
I get an error saying that the gcc version is too recent for the CUDA version that is used.
How do I tell CUDA to use gcc-8 instead of the default one?
I tried to create a symlink for gcc and g++ in the cuda-10.2 path but I get an error telling me the the filesystem is read-only.
```
RUN ln -s /usr/bin/gcc-8 /usr/local/cuda-10.2/bin/gcc && ln -s /usr/bin/g++-8 /usr/local/cuda-10.2/bin/g++
```

What would be the best way to fix this problem?

Thanks

**Comment by timongentzsch** [comment]
Hi, 
you are trying to create a symlink inside the `/usr/local/cuda10-2` folder which is mounted from the host and is read only. To fix your problem, I would overwrite the existing `gcc` symlink in `/usr/bin` instead.

However, to do it a bit more elegantly, I would recommend using apt alternatives. 
To be more specific, the command in your dockerfile should be as follows:

```
RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake gcc-8 g++-8 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8 && \
    update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8 && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean 

```
Hope this helps!

**Comment by JeremieBourque1** [comment]
Thanks!

**Comment by thedevleon** [comment]
> Hi, you are trying to create a symlink inside the `/usr/local/cuda10-2` folder which is mounted from the host and is read only. To fix your problem, I would overwrite the existing `gcc` symlink in `/usr/bin` instead.
> 
> However, to do it a bit more elegantly, I would recommend using apt alternatives. To be more specific, the command in your dockerfile should be as follows:
> 
> ```
> RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake gcc-8 g++-8 && \
>     update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8 && \
>     update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8 && \
>     rm -rf /var/lib/apt/lists/* && \
>     apt-get clean 
> ```
> 
> Hope this helps!

I ran into the same issue as well, and it took me some time to figure out this solution before stumbling across this issue.

Surely, more people will be running into this - maybe it would make sense to make it part of the Dockerfile or mention it in the README of the repo?
