### ISSUE TITLE
Could we build opencv in python3.6 in Jetson_Ubuntu20_Images?

### ISSUE THREAD

**Issue by pratik-esr** [timongentzsch/Jetson_Ubuntu20_Images#13]
Hi Timon, Is it possible to build opencv in python3.6 in Jetson_Ubuntu20_Images ? If yes, could you point me to some ways to do it?

**Comment by timongentzsch** [comment]
first you need ` ppa:deadsnakes/ppa` . repositories available via:
```
add-apt-repository ppa:deadsnakes/ppa
```
after that you should be able to install python3.6: 
```
apt-get update && \
    apt-get install -y --no-install-recommends python3.6-dev python3-pip
```
You can now install opencv pythonbindings either by `pip` (`python3.6 -m pip install opencv-python` or  if you want to have CUDA support refer to my opencv source build dockerfile and add the relevant CMake flag to point it to the right python3 version.

**Comment by pratik-esr** [comment]
After trying out your above steps, it worked. Thanks :-)
