### ISSUE TITLE
Has this repo been hacked?

### ISSUE THREAD

**Issue by brianlmerritt** [timongentzsch/Jetson_Ubuntu20_Images#16]
The latest commit appears to delete docker run files on the Jetson and install a script that always runs on any terminal opened.  All commits prior to the latest commit were signed, the latest commit was not.

The documentation appears to reflect the original code, not the new scripts here which I think should not be run unless the repo owner explains what is going on.

**Comment by timongentzsch** [comment]
Hi @brianlmerritt ,
I just checked the commit from March 8, seems to be ok from my side. 

I don’t know from which commit you re coming from but i recently added the docker autocomplete functionality to my scripts, which I source in .bashrc file

**Comment by brianlmerritt** [comment]
Thank you for coming back so quickly.  You might want to update your documentation on scripts as the script name has changed.
