### ISSUE TITLE
How can I create an OpenCV 4.2 package?

### ISSUE THREAD

**Issue by fig-shimooka** [timongentzsch/Jetson_Ubuntu20_Images#9]
I am using the ros2 image.
I want to use navigation2, but I can't because the OpenCV versions don't match.
How can I get the package for OpenCV4.2?

**Comment by amfern** [comment]
You can compile opencv 4.2 on ubuntu 20.04 and use that, here are instructions to do it https://linuxize.com/post/how-to-install-opencv-on-ubuntu-20-04/
